GEMScienceTools/gmpe-smtk

- smtk/intensity_measures.py
- smtk/sm_database.py
- smtk/strong_motion_selector.py
- smtk/trellis/configure.py
- smtk/trellis/trellis_plots.py
Fixes:
i. Adds "backarc" term to RecordSite and propagates to SiteContext
ii. Adds "ry0" term to RecordDistance and propagates to DistancesContext
iii. Fixes some minor plotting issues
> Multiple Fixes to GMPE Tools

- smtk/parsers/simple_flatfile_parser_sara.py
- smtk/sm_database.py
Adds the revised flatfile parser for the SARA simple flatfile coded by Marlon (https://github.com/GEMScienceTools/gmpe-smtk/pull/17) as a new class SimpleFlatFileParserV9, but retains the original flatfile to ensure backward compatibility with the old v6 of the flatfile.
Increases documentation of methods in sm_database
Add new methods into the sm_database.RecordSite class to return a Eurocode8 and/or NEHRP site class from Vs30 and/or NSPT.
> Adds revised flatfile parser + new database methods

- smtk/parsers/simple_flatfile_parser.py
- smtk/parsers/simple_flatfile_parser_sara.py
- smtk/sm_database.py
- smtk/trellis/trellis_plots.py
Implements new changes in SARA flatfile to take into account finite-fault distance metrics.
Re-implements changes from Stéphane Drouet & Marlon Pirchner - given in PR https://github.com/GEMScienceTools/gmpe-smtk/pull/22
> Updates SARA flatfile parsers

- smtk/intensity_measures.py
- smtk/parsers/simple_flatfile_parser_sara.py
- smtk/sm_database.py
- smtk/trellis/configure.py
- smtk/trellis/trellis_plots.py
A series of small fixes:
1. Adds some features indicated here https://github.com/GEMScienceTools/gmpe-smtk/pull/32 - more to follow
2. Modifies the trellis plots so that the plotted period range is that set by the user and not just that of the narrowest band GMPE
> Fixes August 2015

- smtk/parsers/simple_flatfile_parser_sara.py
- smtk/sm_database.py
Adds non-clashing changes from Stéphane's pull request: https://github.com/GEMScienceTools/gmpe-smtk/pull/32
> Adds minor changes to sara parser and sm_database

- smtk/hazard/conditional_simulation.py
- smtk/intensity_measures.py
- smtk/trellis/configure.py
- smtk/trellis/trellis_plots.py
Changes to the management of contexts in the oq-hazardlib require a couple of small edits in the smtk to propagate them. These are added here.
Also addresses this bug: https://github.com/GEMScienceTools/gmpe-smtk/issues/39
> Updates smtk for changes in hazardlib context, plus minor fix

- smtk/parsers/simple_flatfile_parser_sara.py
- smtk/residuals/gmpe_residuals.py
- smtk/residuals/residual_plotter.py
- smtk/sm_database.py
- smtk/sm_database_builder.py
1. Add RotD50 component
2. Add near-fault directivity index, rcdpp into the database.
> Add RotD50 and Rcdpp

- smtk/parsers/esm_database_parser.py
- smtk/sm_database.py
- smtk/sm_utils.py
Adds the parser to read strong motion records in the European Strong Motion Database format. Adds in new information into the strong motion database.
More information on the ESM database format can be found here: http://esm.mi.ingv.it/static_stage/doc/manual_ESM.pdf
Note that the displacement and velocity time-series files are not parsed, but the SD and PSV are.
> Support for European Strong Motion Database Format

- smtk/hazard/conditional_simulation.py
Reflected the changes in hazardlib and engine
> Fixed commonlib imports

- smtk/parsers/simple_flatfile_parser_sara.py
Fix an error in simple_flatfile_parser_sara.py for calling deepcopy.
> fix calling deepcopy

- smtk/parsers/esm_flatfile_parser.py
- smtk/parsers/valid.py
- smtk/residuals/gmpe_residuals.py
- smtk/sm_database.py
- smtk/strong_motion_selector.py
- smtk/trellis/configure.py
- smtk/trellis/trellis_plots.py
Several changes:
1. Implements the multivariate log-likelihood methodology of Mak et al (2017)
2. Adds new controlling keywords to  trellis plots
3. New selection methods (by site ids, event ids, record ids, distances from faults/interfaces, forearc/backarc etc.)
4. Some cleanup of bugs/doc-strings
> Implements Multivariate Log-likelihood (plus cleanup/fixes)

- smtk/hazard/conditional_simulation.py
Fixes the error in https://travis-ci.org/GEMScienceTools/gmpe-smtk/builds/363771810.
> Reflected changes in hazardlib.correlation

- smtk/trellis/configure.py
Companion of https://github.com/gem/oq-engine/pull/3673.
> Removed mesh_spacing from PlanarSurfaces

- smtk/hazard/conditional_simulation.py
- smtk/sm_database.py
Companion to https://github.com/gem/oq-engine/pull/3683
> Fixed the ContextMaker according to the recent changes in hazardlib

- smtk/trellis/configure.py
- smtk/trellis/trellis_plots.py
This PR adds support for the `azimuth` parameter and cleans some PEP8 issues
> Adding azimuth param + PEP8 clean up

- smtk/trellis/configure.py
- smtk/trellis/trellis_plots.py
Companion of https://github.com/gem/oq-engine/pull/3852. These are mostly PEP8 fixes.
> Reflected changes in the engine

- smtk/database_visualiser.py
- smtk/parsers/asa_database_parser.py
- smtk/parsers/general_flatfile_parser.py
- smtk/residuals/gmpe_residuals.py
- smtk/sm_database.py
- smtk/strong_motion_selector.py
More changes for analysis of Mexican strong motion data. In particular:
- ability to parse CIRES data from Mexico City
- new selector methods for excluding sites by attribute and excluding stations within region
- plot magnitude vs distance by tectonic region
- changes to be compatible with Python 3
> Modifications for strong motion analysis in Mexico

- smtk/hazard/conditional_simulation.py
- smtk/sm_database.py
Companion of https://github.com/gem/oq-engine/pull/4028.
> Fixed test

- smtk/hazard/conditional_simulation.py
- smtk/sm_database.py
- smtk/trellis/configure.py
Companion  of https://github.com/gem/oq-engine/pull/4104
> Fixes due to the change in vs30measured

- smtk/hazard/conditional_simulation.py
Now it should work with all versions of the engine, including master.
> Fixed an error cause by a change engine-side

- smtk/hazard/conditional_simulation.py
- smtk/sm_database_builder.py
- tests/trellis/trellis_test.py
Also skipped the unmaintained tests for the Trellis plots and a misprint in conditional_simulation.py
> Fixed the SMTK to work with h5py > 3

- smtk/residuals/gmpe_residuals.py
> handle non-finite numbers in `get_multivariate_ll` and `_get_edr` + small code optimizations
