- smtk/intensity_measures.py
- smtk/sm_utils.py
- smtk/smoothing/base.py
- smtk/smoothing/konno_ohmachi.py
Adds new features to generate the horiztonal to vertical spectral ratio for a three component set of ground motion records.
i) Adds new tool features for spectral smoothing, including the Konno & Ohmachi (1998) methodology taken from Obspy
ii) Adds get_hvsr method to intensity measures modules.
> Adds spectral smoothing and HVSR

- smtk/parsers/simple_flatfile_parser.py
- smtk/parsers/simple_flatfile_parser_sara.py
For some reason, the distances rjb, rrup, rx and ry0 were stored as lists of single numbers for each record when executing the parsers, which ended up in having lists of lists when using the db.get_context method.
> Modify parsers such that distances are stored as floats and not lists.

- smtk/hazard/conditional_simulation.py
- smtk/sm_database.py
- smtk/strong_motion_selector.py
Removes the dependency on openquake.nrmllib for reading in the rupture model in the conditional gmfs tools. Replaced with openquake.commonlib parser for the rupture file
Fixes the typos noted in this PR: https://github.com/GEMScienceTools/gmpe-smtk/pull/27
> Removes nrmllib dependency plus typo fixes

- smtk/residuals/gmpe_residuals.py
- smtk/residuals/residual_plotter.py
- smtk/sm_database.py
- smtk/trellis/configure.py
- smtk/trellis/trellis_plots.py
Recent application of the GMPE-SMTK in a project identified the following bugs/features needed:
1. Support for trellis plotting and residual calculations when GMPEs are defined in the form of tables. These should be input as strings in the gmpe_list as follows:
`GMPETable(gmpe_table='path/to/my_gmpe_table.hdf5')`
The key will appear as `my_gmpe_table` in the plots (so don't re-use the same filename for different models). Seemingly, this requires that the GMPE table hdf5 file is placed in a directory at at the same level or lower than that of the invoking script/notebook - an OpenQuake issue.
2. The inter-event residual term, whilst being calculated correctly for each record, is being biased with respect to the evaluation statistics in certain cases. The problem originates from the fact …
> Various fixes and features (Dec 2016)

- smtk/trellis/trellis_plots.py
Refactor of the Trellis Plotting to resolve the following issues:
1. Magnitude Trellis and Magnitude-Distance Spectra trellis were lacking methods to instantiate from a rupture model. This is because when the rupture size changes (with magnitude) it would be necessary to rebuild the rupture for each magnitude. This capability has now been added such that the user need only input a single dictionary with the configuration settings of the rupture object in order to get the functionality to work.
2. The ground motion values of the trellis plots can now be exported to json, for easy and organised parsing.
> Revision of Trellis Plots and addition of json exporters

- smtk/trellis/trellis_plots.py
Left over filename input in json exporters. Now no longer used.
> Removes unnecessary json filename input

- smtk/intensity_measures.py
- smtk/response_spectrum.py
- smtk/sm_database.py
- smtk/strong_motion_selector.py
- tests/intensity_measures_test.py
1. Adds preliminary test suite for intensity measures and response spectra (more to follow).
2. More changes for Python 2 & 3 compatibility (Addresses: https://github.com/GEMScienceTools/gmpe-smtk/issues/59)
3. Change `ResponseSpectrum` to replace `evaluate` method with `__call__`. Closes https://github.com/GEMScienceTools/gmpe-smtk/issues/59
From this point onward response spectra should be called with 
```python
nigam_jennings = rsp.NigamJennings(x_record, x_time_step, periods, damping=0.05, units="cm/s/s")
sax, time_series, acc, vel, dis = nigam_jennings()
```
or
```python
sax, time_series, acc, vel, dis = rsp.NigamJennings(x_record, x_time_step, periods, damping=0.05, units="cm/s/s")()
```
> Adds IMS and response spectra tests

- .travis.yml
Whilst Python 3.5/3.6 migration is underway, this temporarily removes Python 3 from travis CI
> Removes Python 3.5, 3.6 from .travis.yml

- smtk/residuals/gmpe_residuals.py
- smtk/trellis/trellis_plots.py
This fixes an error caused by a module rename in hazardlib.
> Renamed gsim_table -> gmpe_table

- smtk/parsers/asa_database_parser.py
- tests/parsers/asa_parser_test.py
The coordinates in the ASA files are given in terms of N S E W directions. Coordinates in the western hemisphere (i.e. Mexico) should be made negative to be consistent with the OQ convention.
> Coordinates

- smtk/trellis/configure.py
- smtk/trellis/trellis_plots.py
- tests/trellis/trellis_test_from_properties.py
TBD:
- Check function names (I inferred from the code, there might be better scientific names, maybe )
- '_append_target_sites' where I set the 'spacing' key for given distances (hope it makes sense).
- Tests: I tested with the newly implemented test 'trellis_test_from_properties' which is a modification of the original 'trellis_test' (which does not break). I did not run all other tests though.
> implements 'from_rupture_properties' methods in Trellis classes

- smtk/trellis/trellis_plots.py
- tests/trellis/trellis_test_todict.py
- Fixes: 
1. a bug whereby empty Python lists where returned from within the `get_ground_motion_values*` methods. This lead to an `AttributeError` in the `to_dict` method trying to `flatten` a (empty) Python list. All `get_ground_motion_values*` now return `numpy` arrays.
2. a bug whereby NaNs where encoded in the `to_dict` method of `MagnitudeDistance`* classes. Now None's are returned.
Added test for the `Distance` trellis class for case 1 and `MagnitudeDistance` trellis class for case 2 (with the parameter set whereby I found the bugs). Missing tests for the `Magnitude` trellis class as I could not programmatically create the right parameter set.
- Fixed missing imports of `os` and `sys` forgot by some other contribution
- Changed the argument name `imt` of `from_rupture_parameter` in …
> Bug fix(es) in trellis_plots.py

- smtk/residuals/gmpe_residuals.py
- smtk/residuals/residual_plots.py
- smtk/residuals/residual_plotter.py
- tests/residuals/residual_plots_test.py
- tests/residuals/residual_plotter_test.py
- tests/residuals/residuals_test.py
Addresses https://github.com/GEMScienceTools/gmpe-smtk/issues/97
The use of subclasses for different tools to calculate the fit of ground motions to models (e.g. `Likelihood`, `LLH`, `MultivariateLLH`, `EDR`) meant that the user would need to re-calculate the residuals upon calling each tool. This PR merges the respective tools into the main Residuals class to avoid this.
The changes (from the original classes to new methods in the Residuals class) are as follows:
`Likelihood` now becomes `.get_likelihood_values()`
`LLH(...)` now becomes `.get_loglikelihood_values(imts)`
`MultivariateLLH` now becomes `.get_multivariate_loglikelihood_values(sum_imts=bool)`
`EDR` now becomes `.get_edr_values(bandwidth, multiplier)`
Additionally, the methods are also added into a dictionary, allowing them to …
> Refactor of Residuals object - merging all methods into one class

- smtk/residuals/gmpe_residuals.py
- smtk/residuals/residual_plots.py
- smtk/sm_table.py
- tests/residuals/residual_plots_test.py
- tests/sm_table_test.py
This PR fixes mainly two things:
1. It handles NaN in residuals plot calculation (this should affect only the case when a user chooses a sm_table instead of a sm_database), using numpy nan-safe methods (nanmean,and so on)
2. Improves the warning and errors to be given when a user uses a numexpr expression for filtering an sm_table
> Handles nans in residuals plots and improves sm_table selection expressions

- smtk/residuals/residual_plots.py
- tests/residuals/residual_plots_test.py
Now residual plots calculate linear regression parameters only on non-nan values of the passed x and y arrays
> implements nanlinregress in residual_plots

- .travis.yml
- smtk/hazard/conditional_simulation.py
In the next version of the engine (3.6) we are going to upgrade numpy to the latest version, 1.16.3. This required some changes, in particular in the correlation model, that required the fixing in the SMTK that you see here. We do not plan to use the newest features from numpy for the moment, so the old version will work. The new numpy is deprecating the matrix class, regular arrays should be used instead and things like `matrix.I, matrix.A1` must be removed.
NB: while at it, I am upgrading the SMTK tests to use pytest, same as for the engine.
> Fixes for the new numpy

- setup.py
- smtk/__init__.py
As discussed, implement a version number that is not the one from the Engine.
The old approach had some ugly side effects: i.e. in an installation from GIT the `__version__` contained the git hash, but not the one from smtk, instead it contained the one from the Engine
This caused some issue while preparing the OpenQuake VM, that's why I'm pushing for these changes.
> Add a own version (with git support) and fix some pep8

- smtk/trellis/configure.py
Companion of https://github.com/gem/oq-engine/pull/5615. Also, removed the Rupture class that was a duplicate of BaseRupture.
> Coped with the removal of slots in hazardlib

- smtk/__init__.py
- smtk/sm_database.py
- tests/database_io_test.py
Fixes a problem whereby `numpy` had to be installed before the program could be installed. This is fine if OpenQuake is already installed, but it breaks third-party installations like [eGSIM](https://github.com/rizac/eGSIM), making their installation still feasible but cumbersome.
What happens is that `setup.py` needs `numpy` because `smtk/__init__.py` implements a `load_database` function. After inspection, that function:
1. has no essential rationale to be imported during installation (`from smtk import load_database` is handy, not essential)
2. regardless of this issue, it really looks like being in the wrong place now, in account of the fact that it refers to only one of the two "databases" implemented in `smtk`
This PR then moves `load_database` into the `sm_database` module, removes …
> moves load_database into sm_database

- smtk/trellis/trellis_plots.py
This PR fixes two minor issues in `trellis_plots.py`:
1. Adds to any generated `dict` the 'imt' key (required by eGSIM)
2. Fixes a minor bug whereby the `ylabel` key of `MagnitudeDistanceSpectraTrellisSigma` was mapped to the y label of the superclass `MagnitudeDistanceSpectraTrellis` (the bug was fixed in the latter by simply calling the class `_get_ylabel` method, as it should be)
3. Cleans up a lot of the module commented line, unused spaces and bad indentations which made the code less readable (unfortunately, these minor fixes make up most of the changes and hide the more important in the comparison)
> Fixing trellis plots

- setup.py
- smtk/rcrs.py
- smtk/sm_database.py
- smtk/sm_table.py
- smtk/sm_table_parsers.py
- smtk/trellis/trellis_plots.py
- tests/trellis/trellis_test.py
- tests/trellis/trellis_test_from_properties.py
This PR does two things:
1. Fixes installation problems by removing matplotlib from setup.py. Not only there is no point in listing a package that is already required by OpenQuake, but **from now, with the new `pip` policiy, the matplotlib version must match that of Openquake, otherwise the install would fail**.
2. Improves the Gsim names returned by Trellis plot output, which might confuse the user (if one passes `"AkkarEtAlRjb2014"` he/she gets results for `"AkkarEtAlRjb2014(adjustment factor=0.0)"`). The standard old behaviour is still maintained if one passes Gsim as class instance. However, if the Gsim is passed as string, return the input string instead (without the Gsim default parameters used, if any).
(implementation detail: the `gsims` attribute of the class `BaseTrellis` is not …
> Improves gsim strings in trellis and fixes setup.py issue with new pip policy

- smtk/rcrs.py
- smtk/residuals/gmpe_residuals.py
- tests/residuals/residual_plots_test.py
Fixes the error in https://github.com/GEMScienceTools/gmpe-smtk/runs/1899995211?check_suite_focus=true:
```python
def get_phi(self, C, mag, sites, nl0):
"""
Returns the within-event variability described in equation 13, line 3
"""
phi = C["sig3"] * np.ones(sites.vs30.shape)
>       phi[sites.vs30measured] = 0.7
E       IndexError: arrays used as indices must be of integer (or boolean) type
```
Plus some PEP8 fixes.
> Fixed the tests for boolean fields in the site collection

- setup.py
A confusing ValueError raised while running `pip install' could be fixed by stripping and replacing newlines with spaces in the field `description` of `setup.py` (tested with Python 3.9.7)
> fix installation bug: remove newlines from setup.py description
